apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: middleware-test
spec:
  rules:
  - host: testing.test.io
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 8080
        path: /
        pathType: Exact