name: Deploy to AKS

on: [push]

env:
  CLUSTER_NAME: TraefikDemo

concurrency: pushing

jobs:

  Apply-yaml:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az aks get-credentials -g TraefikDemo -n $CLUSTER_NAME
          kubectl get ns 