name: Deploy to AKS

on:
  workflow_dispatch
  workflow_run:
    workflows: [Create Traefik demo AKS cluster]
    types:
      - completed

env:
  CLUSTER_NAME: TraefikDemo

concurrency: pushing

jobs:
  Apply-yaml:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: TraefikDemo
        cluster-name: TraefikDemo

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3

    - name: Run script
      run: |
        kubectl get nodes
        kubectl get ns
        kubectl apply -k yaml/